name: Docker Image

on:
  push:
    branches: 
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
     
    steps:
    - name: Change Permissions
      run: ls -l
    - name: Checkout the repository
      uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags:  |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:1.0.${{github.run_number}}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}
          org.opencontainers.image.description="Docker image for displaying home automation related information"
